# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ville.create(name:'Casablanca')
Ville.create(name:'Fes')
Ville.create(name:'Sale')
Ville.create(name:'Marrakesh')
Ville.create(name:'Tangier')
Ville.create(name:'Rabat')
Ville.create(name:'Meknes')
Ville.create(name:'Oujda')
Ville.create(name:'Kenitra')
Ville.create(name:'Agadir')
Ville.create(name:'Tetouan')
Ville.create(name:'Safi')
Ville.create(name:'Temara')
Ville.create(name:'Inzegan')
Ville.create(name:'Mohammedia')
Ville.create(name:'Laayoune')
Ville.create(name:'Khouribga')
Ville.create(name:'Beni Mellal')
Ville.create(name:'Jdida')
Ville.create(name:'Taza')
Ville.create(name:'Ait Melloul')
Ville.create(name:'Nador')
Ville.create(name:'Settat')
Ville.create(name:'Ksar El Kbir')
Ville.create(name:'Larache')
Ville.create(name:'Khemisset')
Ville.create(name:'Guelmim')
Ville.create(name:'Berrechid')
Ville.create(name:'Wad Zam')
Ville.create(name:'Fkih Ben Saleh')
Ville.create(name:'Taourirt')
Ville.create(name:'Berkane')
Ville.create(name:'Sidi Slimane')
Ville.create(name:'Errachidia')
Ville.create(name:'Sidi Kacem')
Ville.create(name:'Khenifra')
Ville.create(name:'Tifelt')
Ville.create(name:'Essaouira')
Ville.create(name:'Taroudant')
Ville.create(name:'El Kelaa des Sraghna')
Ville.create(name:'Oulad Teima')
Ville.create(name:'Youssoufia')
Ville.create(name:'Sefrou')
Ville.create(name:'Ben Guerir')
Ville.create(name:'Tan-Tan')
Ville.create(name:'Ouazzane')
Ville.create(name:'Guercif')
Ville.create(name:'Dakhla')
Ville.create(name:'Hoceima')
Ville.create(name:'Fnideq')
Ville.create(name:'Ouarzazate')
Ville.create(name:'Tiznit')
Ville.create(name:'Suq Sebt Oulad Nama')
Ville.create(name:'Azrou')
Ville.create(name:'Lahraouyine')
Ville.create(name:'Ben Slimane')
Ville.create(name:'Midelt')
Ville.create(name:'Jerada')
Ville.create(name:'Skhirat')
Ville.create(name:'Souk Larbaa')
Ville.create(name:'Ain Harrouda')
Ville.create(name:'Boujad')
Ville.create(name:'Kasbat Tadla')
Ville.create(name:'Sidi Bennour')
Ville.create(name:'Martil')
Ville.create(name:'Lqliaa')
Ville.create(name:'Cape Bojador')
Ville.create(name:'Azemmour')
Ville.create(name:'Mdiq')
Ville.create(name:'Tinghir')
Ville.create(name:'Al Aaroui')
Ville.create(name:'Chefchaouen')
Ville.create(name:'MRirt')
Ville.create(name:'Zagora')
Ville.create(name:'El Aioun Sidi Mellouk')
Ville.create(name:'Lamkansa')
Ville.create(name:'Smara')
Ville.create(name:'Taounate')
Ville.create(name:'Bin AnÅŸÄr')
Ville.create(name:'Sidi Yahya El Gharb')
Ville.create(name:'Zaio')
Ville.create(name:'Amalou Ighriben')
Ville.create(name:'Asilah')
Ville.create(name:'Azilal')
Ville.create(name:'Mechra Bel Ksiri')
Ville.create(name:'El Hajeb')
Ville.create(name:'Bouznika')
Ville.create(name:'Imzouren')
Ville.create(name:'Tahla')
Ville.create(name:'BouiZazarene Ihaddadene')
Ville.create(name:'Ain El Aouda')
Ville.create(name:'Bouarfa')
Ville.create(name:'Arfoud')
Ville.create(name:'Demnate')
Ville.create(name:'Sidi Slimane Echcharraa')
Ville.create(name:'Zaouiat Cheikh')
Ville.create(name:'Ain Taoujdate')
Ville.create(name:'Echemmaia')
Ville.create(name:'Aourir')
Ville.create(name:'Sabaa Aiyoun')
Ville.create(name:'Oulad Ayad')
Ville.create(name:'Ben Ahmed')
Ville.create(name:'Tabounte')
Ville.create(name:'Jorf El Melha')
Ville.create(name:'Missour')
Ville.create(name:'Laattaouia')
Ville.create(name:'Er-Rich')
Ville.create(name:'Segangan')
Ville.create(name:'Rissani')
Ville.create(name:'Sidi Taibi')
Ville.create(name:'Sidi Ifni')
Ville.create(name:'Ait Ourir')
Ville.create(name:'Ahfir')
Ville.create(name:'El Ksiba')
Ville.create(name:'El Gara')
Ville.create(name:'Drarga')
Ville.create(name:'Imintanoute')
Ville.create(name:'Goulmima')
Ville.create(name:'Karia Ba Mohamed')
Ville.create(name:'Mehdya')
Ville.create(name:'El Borouj')
Ville.create(name:'Bouhdila')
Ville.create(name:'Chichaoua')
Ville.create(name:'Bni Bouayach')
Ville.create(name:'Oulad Berhil')
Ville.create(name:'Jmaat Shaim')
Ville.create(name:'Bir Jdid')
Ville.create(name:'Tata')
Ville.create(name:'Boujniba')
Ville.create(name:'Temsia')
Ville.create(name:'Mediouna')
Ville.create(name:'Kalaat MGouna')
Ville.create(name:'Sebt Gzoula')
Ville.create(name:'Outat El Haj')
Ville.create(name:'Imouzzer Kandar')
Ville.create(name:'Ain Bni Mathar')
Ville.create(name:'Bouskoura')
Ville.create(name:'Agourai')
Ville.create(name:'Midar')
Ville.create(name:'Lalla Mimouna')
Ville.create(name:'Ribat El Kheir')
Ville.create(name:'Moulay Driss Zerhoun')
Ville.create(name:'Figuig')
Ville.create(name:'Boumia')
Ville.create(name:'Tamallalt')
Ville.create(name:'Nouaceur')
Ville.create(name:'Rommani')
Ville.create(name:'Jorf')
Ville.create(name:'Ifran')
Ville.create(name:'Bouizakarn')
Ville.create(name:'Oulad Mbarek')
Ville.create(name:'Afourar')
Ville.create(name:'Zmamra')
Ville.create(name:'Ait Ishaq')
Ville.create(name:'Tit Mellil')
Ville.create(name:'Assa')
Ville.create(name:'Bhalil')
Ville.create(name:'Targuist')
Ville.create(name:'Beni Yakhlef')
Ville.create(name:'El Menzel')
Ville.create(name:'Aguelmous')
Ville.create(name:'Sid LMokhtar')
Ville.create(name:'Boumalne Dades')
Ville.create(name:'Farkhana')
Ville.create(name:'Oulad Abbou')
Ville.create(name:'Amizmiz')
Ville.create(name:'Boulanouare')
Ville.create(name:'Ben Taieb')
Ville.create(name:'Ouled Frej')
Ville.create(name:'Driouch')
Ville.create(name:'Deroua')
Ville.create(name:'Hattane')
Ville.create(name:'El Marsa')
Ville.create(name:'Tamanar')
Ville.create(name:'Ait Iaaza')
Ville.create(name:'Sidi Allal El Bahraoui')
Ville.create(name:'Dar Ould Zidouh')
Ville.create(name:'Sid Zouine')
Ville.create(name:'Boudnib')
Ville.create(name:'Foum Zguid')
Ville.create(name:'Tissa')
Ville.create(name:'Jaadar')
Ville.create(name:'Oulmes')
Ville.create(name:'Bouknadel')
Ville.create(name:'Harhoura')
Ville.create(name:'El Guerdan')
Ville.create(name:'Selouane')
Ville.create(name:'Maaziz')
Ville.create(name:'Oulad MRah')
Ville.create(name:'Loudaya')
Ville.create(name:'Massa')
Ville.create(name:'Aklim')
Ville.create(name:'Ouaouizert')
Ville.create(name:'Bni Drar')
Ville.create(name:'El Kbab')
Ville.create(name:'Oued Amlil')
Ville.create(name:'Sidi Rahel Chatai')
Ville.create(name:'Guigou')
Ville.create(name:'Agdz')
Ville.create(name:'Khnichet')
Ville.create(name:'Karia')
Ville.create(name:'Sidi Ahmed')
Ville.create(name:'Zag')
Ville.create(name:'Oulad Yaich')
Ville.create(name:'Tinjdad')
Ville.create(name:'Ouad Laou')
Ville.create(name:'Tighassaline')
Ville.create(name:'Tounfit')
Ville.create(name:'Bni Tadjite')
Ville.create(name:'Bouanane')
Ville.create(name:'Oulad Hriz Sahel')
Ville.create(name:'Talsint')
Ville.create(name:'Taghjijt')
Ville.create(name:'Boulemane')
Ville.create(name:'Zirara')
Ville.create(name:'Taouima')
Ville.create(name:'Tahannaout')
Ville.create(name:'Bradia')
Ville.create(name:'Moulay Abdallah')
Ville.create(name:'Sidi Rahal')
Ville.create(name:'Tameslouht')
Ville.create(name:'Aghbala')
Ville.create(name:'El Ouatia')
Ville.create(name:'Tendrara')
Ville.create(name:'Taznakht')
Ville.create(name:'Fam El Hisn')
Ville.create(name:'Akka')
Ville.create(name:'Dar Gueddari')
Ville.create(name:'Itzer')
Ville.create(name:'Taliouine')
Ville.create(name:'Oualidia')
Ville.create(name:'Aoulouz')
Ville.create(name:'Moulay Bousselham')
Ville.create(name:'Tarfaya')
Ville.create(name:'Ghafsai')
Ville.create(name:'Foum Jamaa')
Ville.create(name:'Ain Leuh')
Ville.create(name:'Moulay Bouazza')
Ville.create(name:'Kariat Arkmane')
Ville.create(name:'Kehf Nsour')
Ville.create(name:'Sidi Bou Othmane')
Ville.create(name:'Oulad Tayeb')
Ville.create(name:'Had Kourt')
Ville.create(name:'Bab Berrad')
Ville.create(name:'Loulad')
Ville.create(name:'Zaida')
Ville.create(name:'Tafrawt')
Ville.create(name:'Khemis Sahel')
Ville.create(name:'Ait Baha')
Ville.create(name:'Biougra')
Ville.create(name:'Dar Bni Karrich')
Ville.create(name:'El Hanchane')
Ville.create(name:'Sidi Jaber')
Ville.create(name:'Irherm')
Ville.create(name:'Debdou')
Ville.create(name:'Ras Kebdana')
Ville.create(name:'Laaounate')
Ville.create(name:'Hadj Kaddour')
Ville.create(name:'Skhour Rhamna')
Ville.create(name:'Bzou')
Ville.create(name:'Ain Cheggag')
Ville.create(name:'Bouderbala')
Ville.create(name:'Sidi Smail')
Ville.create(name:'Oulad Zbair')
Ville.create(name:'Bni Chiker')
Ville.create(name:'Lakhsas')
Ville.create(name:'Talmest')
Ville.create(name:'Aknoul')
Ville.create(name:'Tiztoutine')
Ville.create(name:'Bab Taza')
Ville.create(name:'Imouzzer Marmoucha')
Ville.create(name:'Gourrama')
Ville.create(name:'Ajdir')
Ville.create(name:'Mhaya')
Ville.create(name:'Oulad Ghadbane')
Ville.create(name:'Zrarda')
Ville.create(name:'Zoumi')
Ville.create(name:'Ain Karma')
Ville.create(name:'Thar Essouk')
Ville.create(name:'Lagouira')
Ville.create(name:'Ras El Ain')
Ville.create(name:'Sidi Ali Ben Hamdouche')
Ville.create(name:'Sebt Jahjouh')
Ville.create(name:'Tiddas')
Ville.create(name:'Zaouiat Bougrin')
Ville.create(name:'Tafersit')
Ville.create(name:'Touissit')
Ville.create(name:'Saidia')
Ville.create(name:'Lalla Takerkoust')
Ville.create(name:'Skhinate')
Ville.create(name:'Moulay Brahim')
Ville.create(name:'Soualem')
Ville.create(name:'Gueznaia')
Ville.create(name:'Moulay Yacoub')
Ville.create(name:'Sidi Allal Tazi')
Ville.create(name:'Laakarta')
Ville.create(name:'Alnif')
Ville.create(name:'Dar El Kebdani')
Ville.create(name:'Jebha')
Ville.create(name:'Ain Erreggada')
Ville.create(name:'Sidi Addi')
Ville.create(name:'Skoura')
Ville.create(name:'Smimou')
Ville.create(name:'Ain Jemaa')
Ville.create(name:'Timahdite')
Ville.create(name:'Ait Daoud')
Ville.create(name:'Souk El Had')
Ville.create(name:'Had Bouhssoussen')
Ville.create(name:'Oulad Said')
Ville.create(name:'Arbaoua')
Ville.create(name:'Ain Dorij')
Ville.create(name:'Madagh')
Ville.create(name:'Tighza')
Ville.create(name:'Matmata')
Ville.create(name:'Kerouna')
Ville.create(name:'Kassita')
Ville.create(name:'Bni Hadifa')
Ville.create(name:'Oued El Heimar')
Ville.create(name:'Kerrouchen')
Ville.create(name:'Tainaste')
Ville.create(name:'Guisser')
Ville.create(name:'Sidi Boubker')
Ville.create(name:'Tamassint')
Ville.create(name:'Assahrij')
Ville.create(name:'Aghbalou Nssardane')
Ville.create(name:'Tizi Ouasli')
Ville.create(name:'Moqrisset')
Ville.create(name:'Sebt Lamaarif')
Ville.create(name:'Issaguen')
Ville.create(name:'Bouguedra')
Ville.create(name:'Brikcha')
Ville.create(name:'Ighoud')
Ville.create(name:'Ajdir, Taza')
Ville.create(name:'Oulad Amrane')
Ville.create(name:'Kettara')
Ville.create(name:'Aoufous')
Ville.create(name:'Tafetachte')
Ville.create(name:'Naima')
Ville.create(name:'Tnin Sidi Lyamani')
Ville.create(name:'Karia')
Ville.create(name:'NZalat Bni Amar')
Ville.create(name:'Ahrara')
Ville.create(name:'Sidi Abdallah Ghiat')
Ville.create(name:'Sidi Bouzid')
Ville.create(name:'Ounagha')